title: "[Proposal] "
labels: ["Proposal"]
body:
  - type: textarea
    id: who
    attributes:
      label: Who are you? A little Bio 💞
      description: "Tell us a bit about yourself."
      placeholder: "Your bio here..."
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What do you want to talk about? 🗣️
      description: "Describe the topic of your proposal."
      placeholder: "Your topic here..."
    validations:
      required: true
  - type: textarea
    id: where_when
    attributes:
      label: Where / When - What's your availability? 📆
      description: "Let us know your availability for presenting this talk."
      placeholder: "Your availability here..."
    validations:
      required: true
  - type: textarea
    id: prior_work
    attributes:
      label: Do you have any prior work regarding this topic?
      description: "Please share links to repositories, webpages, articles, tweets, etc., related to your topic."
      placeholder: "Links to your prior work here..."
  - type: markdown
    attributes:
      value: |
        ### Thank you for your submission
        We look forward to reviewing your proposal!
