name: Create Image PR

on:
  workflow_call:
    inputs:
      date:
        description: 'Event Date (YYYY-MM-DD)'
        required: true
        type: string
      image:
        description: 'Image Type (banner, meetup)'
        default: banner
        type: string

jobs:
  create-banner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate unique branch name
        id: generate-branch-name
        run: |
          # Using a combination of the event date and a unique suffix (UUID)
          echo "BRANCH_NAME=image-${{inputs.image}}-${{ inputs.date }}-$(uuidgen)" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create new branch
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Create Image
        run: |
          npm i tsx -g
          cd ./packages/image-generator
          npm i
          cd ../..

          # Create directory if it doesn't exist
          mkdir -p ./public/${{inputs.image}}
          
          tsx --tsconfig ./packages/image-generator/tsconfig.json ./packages/image-generator/cli.ts --image ${{ inputs.image }} --date ${{ inputs.date }} > ./public/${{inputs.image}}/${{ inputs.date }}.png

      - name: Commit files
        run: |
          git add .
          git commit -m "Add image "${{ inputs.image }}" for ${{ inputs.date }}"

      - name: Push changes
        run: git push origin ${{ env.BRANCH_NAME }}

      - name: Create PR
        uses: actions/github-script@v6
        with:
          script: |
            const headBranch = process.env.BRANCH_NAME;
            const baseBranch = 'main'; // Ensure this matches your repo's default branch

            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Generated image "${{ inputs.image }}" for ${{ inputs.date }}`,
              head: headBranch,
              base: baseBranch,
              body: 'This PR adds a new image ${{ inputs.image }}.',
            });
