name: Create Banner on Dispatch

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Event Date (YYYY-MM-DD)'
        required: true

jobs:
  create-banner-on-dispatch:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Banner
      uses: ./.github/workflows/_create-banner.yml@main
      with:
        date: ${{ github.event.inputs.date }}